[Eth]
NetworkId = 17243
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 5000000000
Recommit = 10000000000
Noverify = false

[Eth.Ethash]
CacheDir = ""
CachesInMem = 0
CachesOnDisk = 0
CachesLockMmap = false
DatasetDir = ""
DatasetsInMem = 0
DatasetsOnDisk = 0
DatasetsLockMmap = false
PowMode = 0

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60

[Node]
DataDir = "node"
InsecureUnlockAllowed = false
NoUSB = true
IPCPath = "geth.ipc"
HTTPHost = "127.0.0.1"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["debug","eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
StaticNodes = []
BootstrapNodes = ["enode://dfe5a80f5bbd7c16c12d64aebbfc31806c6bae138032fcb19f0babc79c94d4f07ca52f5ee981afb92daf5973b621065614345498ac21b4418bf88a1bcad1364c@138.197.189.243:30311"]
TrustedNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

# [Node.LogConfig]
# FileRoot = ""
# FilePath = "chiliz.log"
# MaxBytesSize = 10485760
# Level = "trace"
